### ISSUE TITLE
OAuth requests not working

### ISSUE THREAD

**Issue by Huesdon** [tsifrer/python-twitch-client#4]
My auth token was generated with channel_editor and channel_read scopes.
Validated it by using this on the browser:
https://api.twitch.tv/kraken/channels/pwnographers/editors?client_id=[my client id]&oauth_token=[my auth token]

It returned: {"_links":{"self":"https://api.twitch.tv/kraken/channels/pwnographers/editors"},"users":[]}

However, when I try to use your package as per docs like so....

`>>> from twitch import TwitchClient
>>> client = TwitchClient('[my client id]', '[my auth token]')
>>> channel = client.channels.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Code\dolores\python\twitch\decorators.py", line 8, in wrapper
    return func(*args, **kwargs)
  File "E:\Code\dolores\python\twitch\api\channels.py", line 14, in get
    response = self._request_get('channels')
  File "E:\Code\dolores\python\twitch\api\base.py", line 31, in _request_get
    response.raise_for_status()
  File "C:\Users\Hue\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.twitch.tv/kraken/channels`

**Comment by Huesdon** [comment]
No response but I continued to play with this. What wasn't clear was that I needed a numeric id rather than the literal string name of the channel. (despite the data type being string)

Then my issue was, where the hell do I get my channel id... even a google didn't help there but I pulled the whole channel object and found my id in there.

Once I had the proper id the above call worked as expected.
