### ISSUE TITLE
"self" defined as string?

### ISSUE THREAD

**Issue by XCanG** [tsifrer/python-twitch-client#7]
```
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    posts = api.channel_feed.ChannelFeed.get_posts(str(channel.id), 100)
  File "C:\Python\Python36\lib\site-packages\twitch\api\channel_feed.py", line 22, in get_posts
    response = self._request_get('feed/%s/posts' % channel_id, params=params)
AttributeError: 'str' object has no attribute '_request_get'
```

**Comment by XCanG** [comment]
Oh, sorry, I use wrong path. It `client.channel_feed.get_posts()`
